# Default channel settings for R8FM
# 0 - Roll (right)
# 1 - Pitch (right)
# 2 - Throttle (left)
# 3 - Yaw (left)
# 4 - Right 3-way
# 5 - Right button
# 6 - Left 3-way
# 7 - Left trim POT

ppm_input:
    ros__parameters:
        mode: joy
        # frame_id: preview
        # pin: <rpi gpio pin number, defaults to 7>
        joystick:
            # indexes channel IDs in the received PPM frame
            axis: [0,1,2,3,7]
            buttons: [4,5,6]
            # indicate some buttons are 3-way (have 3 poles)
            3-way: [4,6]

        # per-axis configuration
        axis-0:
            type: midstick
            deadband: 30
        axis-1:
            type: midstick
            deadband: 30
        axis-2:
            type: throttle
        axis-3:
            type: midstick
            deadband: 30
        axis-4:
            type: trim


